coverage:
  range: 60..80 # test coverage thresholds. 60% and below fails (red), 80% and up passes (green), between is "yellow"
  round: down
  precision: 1
  status:
    project:
      default:
        target: 65% # require new commits to have at least 65% coverage
        threshold: 2% # more than 2% coverage drop, fail.
    patch:
      default:
        enabled: no
ignore:
  - "**/Microsoft.CodeAnalysis.CSharp.Symbols"  # ignore folders and all its contents
  - "**/Microsoft.CodeAnalysis.PooledObjects"  # ignore folders and all its contents
  - "**/Microsoft.CodeAnalysis"  # ignore folders and all its contents
